### ISSUE TITLE
Required Ruby version

### ISSUE THREAD

**Issue by krysztalzg** [rogerluan/arkana#14] opened 2022-07-28 12:27 UTC
Hello, I've noticed that this tool require ruby 2.7+, but by default MacOS and bitrise's Xcode stack are using 2.6.x. It's not a big issue to bump it, but for most developers that don't dabble with ruby it will be additional stepping stone while adding Arkana to their projects. Would it be possible to lower requirement?

**Comment by rogerluan** [comment] 2022-08-02 05:02
Hi @krysztalzg 👋 thanks for this feedback!
I think it wouldn't be too much of a big lift to lower the requirement to 2.6.x - IIRC I am using some set of APIs only available in v2.7.x but I can't recall which ones from the top of my head, so I'd need to test this out. Do you happen to know which specific Ruby version macOS and Bitrise comes with, or should we just attempt to add support to v2.6.0?

Also, would this be something you'd be willing to contribute by opening a PR for? 😊

**Comment by erfanandesta1373** [comment] 2022-08-06 10:09
I have the same issue on Bitrise. Any help on this? @krysztalzg @rogerluan 
<img width="731" alt="Screen Shot 1401-05-15 at 14 38 38" src="https://user-images.githubusercontent.com/77014611/183244426-e3c204b2-1c7e-4759-8953-c51ace94ed44.png">

**Comment by rogerluan** [comment] 2022-08-06 10:55
@erfanandesta1373 I haven't removed v1.1.1 or any other version from RubyGems 🤔 is your issue related to the ruby version?

**Comment by erfanandesta1373** [comment] 2022-08-06 11:45
Actually, the problem is what @krysztalzg explained. Bitrise uses 2.6.9 as it's the latest Xcode ruby installed. I just change the minimum version to 2.6.9 on this [PR](https://github.com/rogerluan/arkana/pull/15) and it's working fine.

**Comment by rogerluan** [comment] 2022-08-06 16:14
#15 was merged! 
I'm going to release it asap.

**Comment by rogerluan** [comment] 2022-08-06 16:29
Released! https://github.com/rogerluan/arkana/releases/tag/v1.2.0 😉 

@krysztalzg @erfanandesta1373 let me know if there are any issues after upgrading to v1.2.0! 💪 

Closing this ticket.

**Closed by rogerluan** 2022-08-06 16:29 UTC
